service: my-lambda-service-3232fert

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  hello:
    handler: handler.hello # Points to the 'hello' function within 'handler.js'
    events:
      - httpApi:
          path: /hello
          method: get