name: Dynamic Workflow and Upload Files
on:
  workflow_dispatch:
    inputs:
      index_document:
        description: 'Name of the index document'
        required: true
        default: 'index.html'
      error_document:
        description: 'Name of the error document'
        required: true
        default: 'error.html'
env:
  BUCKET_NAME: website-artifacts-12223dfsfds43234s
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Seed base creds
        run: |
          aws configure set aws_access_key_id     "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region us-east-1

      - name: Get temp session
        id: sess
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          CREDS=$(aws sts get-session-token --duration-seconds 3600)
          echo "AK=$(echo "$CREDS" | jq -r .Credentials.AccessKeyId)"        >> "$GITHUB_OUTPUT"
          echo "SK=$(echo "$CREDS" | jq -r .Credentials.SecretAccessKey)"    >> "$GITHUB_OUTPUT"
          echo "ST=$(echo "$CREDS" | jq -r .Credentials.SessionToken)"       >> "$GITHUB_OUTPUT"

      - name: Configure AWS credentials (temporary)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ steps.sess.outputs.AK }}
          aws-secret-access-key: ${{ steps.sess.outputs.SK }}
          aws-session-token:     ${{ steps.sess.outputs.ST }}
          aws-region: us-east-1
          
      - name: Create CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: uda-artifact
          template: uda_artifact.yml
          no-fail-on-empty-changeset: "1"
          
      - name: Upload files to S3 bucket
        run: |
          aws s3 cp ./website/${{ github.event.inputs.index_document }} s3://${{env.BUCKET_NAME}} 
          aws s3 cp ./website/${{ github.event.inputs.error_document }} s3://${{env.BUCKET_NAME}} 

      - name: Show S3 bucket website URL
        run: |
          aws cloudformation describe-stacks \
            --stack-name uda-artifact \
            --query 'Stacks[0].Outputs[?OutputKey==`ArtifactBucketWebsiteURL`].OutputValue' \
            --output text

