name: Deploy to AWS Lambda

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: |
        npm ci
        npm install -g serverless@3.36.0

    - name: Deploy to AWS Lambda using Serverless Framework
      run: | 
        serverless deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}