name: 'Terraform'
on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Seed base creds
        run: |
          aws configure set aws_access_key_id     "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region us-east-1

      - name: Get temp session
        id: sess
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          CREDS=$(aws sts get-session-token --duration-seconds 3600)
          echo "AK=$(echo "$CREDS" | jq -r .Credentials.AccessKeyId)"        >> "$GITHUB_OUTPUT"
          echo "SK=$(echo "$CREDS" | jq -r .Credentials.SecretAccessKey)"    >> "$GITHUB_OUTPUT"
          echo "ST=$(echo "$CREDS" | jq -r .Credentials.SessionToken)"       >> "$GITHUB_OUTPUT"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ steps.sess.outputs.AK }}
          aws-secret-access-key: ${{ steps.sess.outputs.SK }}
          aws-session-token:     ${{ steps.sess.outputs.ST }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan
        run: terraform plan 
        continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve
